### PR TITLE
fix(spes-2): symlinks wes url rewrite fix

### PR DESCRIPTION
**Pull request by nishad5**
This PR is related to the ticket https://jira.wiley.com/browse/SPES-2

I have added all information and findings in the confluence at https://confluence.wiley.com/display/SPEK/SPES+2+-+WP+Symlinks+Wes+plugin+defect+fix

@joselogil - Please do review the PR. I cannot tag Matt because I can't find his username here. TIA

### CODE REVIEW

**Review by joselogil — APPROVED** [review]
LGTM

**Review by eriksays — CHANGES_REQUESTED** [review]
please add version update to main file. (symlink-wes.php?)

**Comment by nishad5** [comment]
Hi @eriksays - The version is now updated with a new commit. TIA

**Review by eriksays — APPROVED** [review]
lgtm

**Pull request merged**
